// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using odevKontrol.Models;

#nullable disable

namespace odevKontrol.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241202192809_StudentTable")]
    partial class StudentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("odevKontrol.Models.Homework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("StudentNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Homeworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Kalem açıklama",
                            IsActive = true,
                            Name = "Kalem",
                            StudentNumber = 10L
                        },
                        new
                        {
                            Id = 2,
                            Description = "Defter açıklama",
                            IsActive = true,
                            Name = "Defter",
                            StudentNumber = 15L
                        },
                        new
                        {
                            Id = 3,
                            Description = "Silgi açıklama",
                            IsActive = false,
                            Name = "Silgi",
                            StudentNumber = 20L
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kitap açıklama",
                            IsActive = false,
                            Name = "Kitap",
                            StudentNumber = 30L
                        },
                        new
                        {
                            Id = 5,
                            Description = "Boya açıklama",
                            IsActive = false,
                            Name = "Boya",
                            StudentNumber = 25L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
